server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=melih
spring.jpa.hibernate.ddl-auto=update
spring.application.name=inventory-service
